[package]
name = "hvw-dhcpd"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.5"
log = "0.4"
env_logger = "0.9"
anyhow = "1.0"
pnet = "0.28"
